Move prover returns: exiting with verification errors
error: verification out of resources/timeout (global timeout set to 80s)
    ┌─ ../move-stdlib/sources/fixed_point32.move:264:5
    │
264 │ ╭     public fun round(num: FixedPoint32): u64 {
265 │ │         let floored_num = floor(num) << 32;
266 │ │         let boundary = floored_num + ((1 << 32) / 2);
267 │ │         if (num.value < boundary) {
    · │
271 │ │         }
272 │ │     }
    │ ╰─────^

error: data invariant does not hold
  ┌─ tests/sources/functional/data_invariant_in_map.move:8:9
  │
8 │         invariant value != 0;
  │         ^^^^^^^^^^^^^^^^^^^^^
  │
  =     at tests/sources/functional/data_invariant_in_map.move:20: violation_1
  =     at tests/sources/functional/data_invariant_in_map.move:21: violation_1
  =     at tests/sources/functional/data_invariant_in_map.move:22: violation_1
  =     at tests/sources/functional/data_invariant_in_map.move:23: violation_1
  =         <redacted> = <redacted>
  =         s = <redacted>
  =         <redacted> = <redacted>
  =     at tests/sources/functional/data_invariant_in_map.move:8
